# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file minecraftrpc/pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -f minecraftrpc/pom.xml -s minecraftrpc/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_ACTOR: ${{ github.actor }}

    - name: Find versioned JAR file
      id: find_jar
      run: |
        JAR_FILE=$(ls minecraftrpc/target/minecraftrpc-*.jar | grep -v 'original' | head -n 1)
        echo "jar=$JAR_FILE" >> $GITHUB_OUTPUT
        FILE_NAME=$(basename "$JAR_FILE")
        echo "filename=$FILE_NAME" >> $GITHUB_OUTPUT

    - name: Upload JAR to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.find_jar.outputs.jar }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}