
# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: NPM Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v4
      with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
    - run: npm ci
      working-directory: minecraftrpc.js
    - run: npm publish --provenance --access public
      working-directory: minecraftrpc.js
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    